export const USER_LOGIN = "USER_LOGIN",
 USER_SIGNUP = "USER_SIGNUP",
 SAVE_DISH = 'SAVE_DISH',
 SAVE_FRUIT = 'SAVE_FRUIT',
 CLEAR_ERROR = "CLEAR_ERROR",
 POST_PROFILE_CHANGES = "POST_PROFILE_CHANGES",
 GET_PROFILE = "GET_PROFILE",
 GET_FOODITEM_BY_CATEGORY = "GET_FOODITEM_BY_CATEGORY"


